version: "3.3"

services:
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_DB=the_pokedex
      - POSTGRES_USER=student
      - POSTGRES_PASSWORD=adminStudent
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgressql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@mail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - 5050:80
    volumes:
      - ./pgadmin_data:/var/lib/pgadmin

